device_name = "Pebble K380s"

# FnLock also swaps insert
[[remap]]
input = ["KEY_VOLUMEUP"]
output = ["KEY_INSERT"]

[[remap]]
input = ["KEY_INSERT"]
output = ["KEY_VOLUMEUP"]

# Map screenshot key to PrtSc
[[remap]]
input = ["KEY_LEFTSHIFT", "KEY_LEFTMETA", "KEY_S"]
output = ["KEY_PRINT"]

# Configure CAPSLOCK as a Dual Role key.
# Holding it produces LEFTCTRL, but tapping it
# will produce ESC.
# Both `tap` and `hold` can expand to multiple output keys.
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTSHIFT", "KEY_LEFTCTRL", "KEY_LEFTALT"]
tap = ["KEY_ESC"]

# Vim Keybindings
# ---------------

# Map <M-h/j/k/l> to arrow keys
[[remap]]
input = ["KEY_LEFTALT", "KEY_H"]
output = ["KEY_LEFT"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_J"]
output = ["KEY_DOWN"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_K"]
output = ["KEY_UP"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_L"]
output = ["KEY_RIGHT"]

# Map <M-w/b> to <C-right/left> (forward or back a word)
[[remap]]
input = ["KEY_LEFTALT", "KEY_W"]
output = ["KEY_LEFTCTRL", "KEY_RIGHT"]

[[remap]]
input = ["KEY_LEFTALT", "KEY_B"]
output = ["KEY_LEFTCTRL", "KEY_LEFT"]
