# systemctl abbreviations
abbr -a s 'sudo systemctl'
abbr -a si 'sudo systemctl status'
abbr -a se 'sudo systemctl enable'
abbr -a sd 'sudo systemctl disable'
abbr -a ss 'sudo systemctl start'
abbr -a st 'sudo systemctl stop'
abbr -a sr 'sudo systemctl restart'
abbr -a sl 'sudo systemctl daemon-reload'
abbr -a siu 'systemctl --user status'
abbr -a seu 'systemctl --user enable'
abbr -a sdu 'systemctl --user disable'
abbr -a ssu 'systemctl --user start'
abbr -a stu 'systemctl --user stop'
abbr -a sru 'systemctl --user restart'
abbr -a slu 'systemctl --user daemon-reload'
